version: '3'
services:
  gnpsdatasetchooser-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnpsdatasetchooser-dash
    volumes:
      - ./logs:/app/logs:rw
    ports:
    - "5854:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: gnps-explorer.ucsd.edu
      VIRTUAL_PORT: 5854
      LETSENCRYPT_HOST: gnps-explorer.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu

networks:
  nginx-net:
    external:
      name: nginx-net