version: '3'
services:
  gnpsdatasetchooser-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnpsdatasetchooser-dash
    volumes:
      - ./logs:/app/logs:rw
    ports:
    - "5854:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: explorer.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: explorer.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com

networks:
  nginx-net:
    external:
        name: nginx-net
    
    